package com.animales.app;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity {
    private LinearLayout body;
    private SharedPreferences data;
    private final int GREEN=Color.rgb(21,105,98), DARK=Color.rgb(14,72,68), BG=Color.rgb(247,250,249), TEXT=Color.rgb(35,43,45), MUTED=Color.rgb(101,113,114);
    private static final int PICK_PHOTO=42;
    @Override public void onCreate(Bundle b){super.onCreate(b);data=getSharedPreferences("cachorrito",MODE_PRIVATE);showHome();}
    private int d(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private GradientDrawable shape(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(d((int)r));return g;}
    private GradientDrawable outline(int c,int w,int sc,float r){GradientDrawable g=shape(c,r);g.setStroke(d(w),sc);return g;}
    private TextView txt(String s,float z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.DEFAULT,b?Typeface.BOLD:Typeface.NORMAL);return t;}
    private void add(View v,int top,int bottom){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,d(top),0,d(bottom));body.addView(v,p);}
    private Button btn(String s,boolean filled){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setTextColor(filled?Color.WHITE:DARK);b.setBackground(filled?shape(GREEN,16):outline(Color.WHITE,1,Color.rgb(205,220,216),16));b.setMinHeight(d(52));b.setStateListAnimator(null);return b;}
    private void page(String title,String sub){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(d(20),d(20),d(20),d(18));head.setBackground(shape(DARK,0));head.addView(txt("🐾  "+title,24,Color.WHITE,true));if(sub!=null){TextView s=txt(sub,13,Color.rgb(216,237,233),false);s.setPadding(0,d(5),0,0);head.addView(s);}root.addView(head);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(d(20),d(18),d(20),d(30));ScrollView sv=new ScrollView(this);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    private View card(String title,String sub,String icon,View.OnClickListener c){LinearLayout box=new LinearLayout(this);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(d(15),d(14),d(12),d(14));box.setBackground(outline(Color.WHITE,1,Color.rgb(226,234,231),18));TextView i=txt(icon,25,TEXT,false);i.setGravity(Gravity.CENTER);box.addView(i,new LinearLayout.LayoutParams(d(44),d(44)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(d(12),0,d(5),0);words.addView(txt(title,17,TEXT,true));words.addView(txt(sub,13,MUTED,false));box.addView(words,new LinearLayout.LayoutParams(0,-2,1));box.addView(txt("›",30,GREEN,false),new LinearLayout.LayoutParams(d(22),-2));box.setOnClickListener(c);return box;}
    private void showHome(){String name=data.getString("name","");page("Cachorrito",name.isEmpty()?"Comprende sus señales. Cuídalo mejor.":"Perfil activo: "+name);LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setPadding(d(18),d(20),d(18),d(20));hero.setBackground(shape(Color.rgb(255,246,240),20));hero.addView(txt(name.isEmpty()?"Tu compañero merece ser entendido.":"Hola, humano de "+name+".",23,TEXT,true));TextView h=txt(name.isEmpty()?"Crea su perfil y empieza a observar patrones.":"Registra lo que ves y descubre qué puede estar comunicando.",14,MUTED,false);h.setPadding(0,d(7),0,0);hero.addView(h);add(hero,0,14);add(card("¿Qué está comunicando?","Analiza una señal y descubre interpretaciones posibles.","🔎",v->showSignals()),0,10);add(card("Mi perro","Perfil, foto, raza, edad, peso y necesidades.","🐶",v->showProfile()),0,10);add(card("Historial","Guarda observaciones y vuelve a ellas.","📖",v->showHistory()),0,10);add(card("Biblioteca canina","Lenguaje corporal, contexto y señales de alerta.","📚",v->showGuide()),0,18);add(txt("La clave es el contexto",17,TEXT,true),0,5);add(txt("Postura + cara + cola + entorno + lo que ocurrió antes forman una imagen mucho más útil que una señal aislada.",14,MUTED,false),0,0);}
    private void showProfile(){page("Mi perro","La información se guarda localmente en este teléfono.");ImageView photo=new ImageView(this);photo.setBackground(shape(Color.rgb(233,242,239),50));photo.setScaleType(ImageView.ScaleType.CENTER_CROP);String uri=data.getString("photo","");if(!uri.isEmpty())try{photo.setImageURI(Uri.parse(uri));}catch(Exception ignored){}else photo.setImageResource(android.R.drawable.ic_menu_camera);add(photo,0,12);Button choose=btn("Elegir foto",false);choose.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_PHOTO);});add(choose,0,12);EditText name=field("Nombre",data.getString("name",""));EditText breed=field("Raza",data.getString("breed",""));EditText sex=field("Sexo",data.getString("sex",""));EditText age=field("Edad en años",data.getString("age",""));age.setInputType(2);EditText weight=field("Peso aproximado en kg",data.getString("weight",""));weight.setInputType(2|8192);EditText needs=field("Condiciones, alergias o necesidades especiales",data.getString("needs",""));needs.setMinLines(3);add(name,0,9);add(breed,0,9);add(sex,0,9);add(age,0,9);add(weight,0,9);add(needs,0,14);Button save=btn("Guardar perfil",true);save.setOnClickListener(v->{data.edit().putString("name",name.getText().toString().trim()).putString("breed",breed.getText().toString().trim()).putString("sex",sex.getText().toString().trim()).putString("age",age.getText().toString().trim()).putString("weight",weight.getText().toString().trim()).putString("needs",needs.getText().toString().trim()).apply();Toast.makeText(this,"Perfil guardado",Toast.LENGTH_SHORT).show();showHome();});add(save,0,9);Button back=btn("Volver",false);back.setOnClickListener(v->showHome());add(back,0,0);}
    private EditText field(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setTextSize(15);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setPadding(d(14),0,d(14),0);e.setMinHeight(d(52));e.setBackground(outline(Color.WHITE,1,Color.rgb(218,226,223),14));return e;}
    @Override protected void onActivityResult(int r,int result,Intent i){super.onActivityResult(r,result,i);if(r==PICK_PHOTO&&result==Activity.RESULT_OK&&i!=null&&i.getData()!=null){Uri u=i.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}data.edit().putString("photo",u.toString()).apply();showProfile();}}
    private void showSignals(){page("Lectura de conducta","Elige la señal que más se parece a lo que observas.");add(txt("¿Qué estás viendo?",20,TEXT,true),0,8);String[][] a={{"Cola baja o entre las patas","Puede acompañar miedo, inseguridad o estrés","🐕"},{"Orejas hacia atrás","Puede indicar incomodidad, miedo o apaciguamiento","👂"},{"Jadeo sin ejercicio","Puede relacionarse con calor, excitación, estrés o malestar","💨"},{"Ladrido repetido","Puede ser alerta, excitación, frustración, miedo o atención","🔊"},{"Se esconde o evita contacto","Puede relacionarse con miedo, estrés, dolor o necesidad de espacio","🏠"},{"Cuerpo rígido","Señal importante de tensión; mira el contexto","⚠️"},{"Bosteza o lame el hocico","Puede aparecer en situaciones de tensión, pero no es específica","👅"},{"Cuerpo relajado","Suele ser compatible con comodidad; confirma con el contexto","💚"}};for(String[] x:a)add(card(x[0],x[1],x[2],v->showResult(x[0])),0,9);}
    private void showResult(String signal){page("Lectura","Una señal es una pista, no un diagnóstico.");String meaning="",action="",warning="";if(signal.startsWith("Cola")){meaning="Una cola baja puede aparecer con miedo, inseguridad o estrés. Observa también postura, orejas, mirada y distancia.";action="Dale espacio, evita forzar la interacción y registra qué ocurrió justo antes.";warning="Si el cambio es repentino o hay dolor, conviene una evaluación veterinaria.";}else if(signal.startsWith("Orejas")){meaning="Las orejas hacia atrás pueden acompañar miedo o incomodidad. La forma de las orejas y la raza también importan.";action="Reduce la presión y observa el conjunto del cuerpo.";warning="No etiquetes al perro como agresivo o sumiso por una sola señal.";}else if(signal.startsWith("Jadeo")){meaning="El jadeo es normal después de ejercicio o con calor, pero sin una causa clara puede acompañar estrés o malestar.";action="Comprueba calor, actividad reciente, agua y contexto.";warning="Dificultad respiratoria, debilidad, colapso o jadeo intenso persistente requieren atención veterinaria.";}else if(signal.startsWith("Ladrido")){meaning="El ladrido tiene múltiples funciones. El momento, el estímulo y lo que ocurre después ayudan a interpretarlo.";action="Anota qué pasó antes, durante y después.";warning="Evita castigos físicos o gritos, que pueden aumentar la activación.";}else if(signal.startsWith("Se esconde")){meaning="Evitar contacto puede relacionarse con miedo, estrés, dolor o una experiencia negativa.";action="No lo obligues a salir; ofrece un lugar seguro y reduce la presión.";warning="Si es nuevo, intenso o viene con cambios físicos, consulta.";}else if(signal.startsWith("Cuerpo rígido")){meaning="La rigidez puede indicar tensión, miedo, conflicto o dolor y merece atención al contexto.";action="Aumenta la distancia y evita tocarlo o arrinconarlo.";warning="Si gruñe, muestra dientes o intenta morder, prioriza seguridad y distancia.";}else if(signal.startsWith("Bosteja")){meaning="Bostezar o lamerse el hocico puede aparecer con tensión, pero también tiene funciones normales.";action="Busca otras señales antes de sacar conclusiones.";warning="Si aparece junto a signos físicos anormales, consulta.";}else{meaning="Un cuerpo suelto y movimientos suaves suelen ser compatibles con comodidad.";action="Observa si es habitual para tu perro y qué ocurre alrededor.";warning="La conducta puede cambiar rápido; sigue observando el conjunto.";}
        add(box("¿Qué puede significar?",meaning,"🧠"),0,10);add(box("¿Qué puedes hacer?",action,"✓"),0,10);add(box("Cuándo prestar más atención",warning,"⚠"),0,16);Button save=btn("Guardar observación",true);save.setOnClickListener(v->saveHistory(signal,meaning));add(save,0,9);Button again=btn("Elegir otra señal",false);again.setOnClickListener(v->showSignals());add(again,0,0);}
    private LinearLayout box(String title,String text,String icon){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(16),d(14),d(16),d(14));b.setBackground(outline(Color.WHITE,1,Color.rgb(224,231,228),18));LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.addView(txt(icon,20,TEXT,false));TextView t=txt(title,16,TEXT,true);t.setPadding(d(10),0,0,0);h.addView(t);b.addView(h);TextView q=txt(text,14,MUTED,false);q.setPadding(0,d(7),0,0);b.addView(q);return b;}
    private void saveHistory(String signal,String detail){String old=data.getString("history","");String item=signal+"\n"+detail;String all=item+(old.isEmpty()?"":"\n\n"+old);String[] p=all.split("\\n\\n");StringBuilder out=new StringBuilder();for(int i=0;i<p.length&&i<30;i++){if(i>0)out.append("\n\n");out.append(p[i]);}data.edit().putString("history",out.toString()).apply();Toast.makeText(this,"Observación guardada",Toast.LENGTH_SHORT).show();showHistory();}
    private void showHistory(){page("Historial","Observaciones almacenadas localmente.");String h=data.getString("history","");if(h.isEmpty()){add(txt("Todavía no hay observaciones",21,TEXT,true),0,6);add(txt("Analiza una señal y guárdala para empezar a detectar patrones.",14,MUTED,false),0,18);}else{for(String item:h.split("\\n\\n")){String[] l=item.split("\\n",2);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(d(15),d(13),d(15),d(13));b.setBackground(shape(Color.WHITE,16));addTo(b,txt(l[0],16,TEXT,true));if(l.length>1)addTo(b,txt(l[1],13,MUTED,false));add(b,0,9);}}Button clear=btn("Borrar historial",false);clear.setOnClickListener(v->{data.edit().remove("history").apply();showHistory();});add(clear,8,9);Button back=btn("Volver",false);back.setOnClickListener(v->showHome());add(back,0,0);}
    private void addTo(LinearLayout b,View v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,d(5));b.addView(v,p);}
    private void showGuide(){page("Biblioteca canina","Conceptos rápidos para observar mejor.");add(box("Cola","Mira altura, tensión y movimiento. Una cola moviéndose no significa automáticamente felicidad.","🐕"),0,9);add(box("Orejas y ojos","Observa orientación, tensión, mirada y parpadeo junto con el resto del cuerpo.","👀"),0,9);add(box("Boca","Jadeo, lamido del hocico, bostezos y tensión pueden aportar información contextual.","👄"),0,9);add(box("Cuerpo","Un cuerpo encogido puede sugerir inseguridad; uno rígido puede indicar tensión.","🧍"),0,9);add(box("Contexto","Ruido, personas, otros animales, comida, calor, dolor y cambios recientes pueden modificar la conducta.","🌿"),0,16);add(txt("Importante",19,TEXT,true),0,5);add(txt("Dificultad respiratoria, colapso, convulsiones, sangrado, intoxicación, dolor intenso u otros signos graves no deben manejarse solo con esta aplicación.",14,Color.rgb(150,70,56),false),0,0);}
}
