plugins {
    id 'com.android.application'
}

android {
    namespace 'com.animales.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.animales.app"
        minSdk 21
        targetSdk 35
        versionCode 3
        versionName "2.0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
}
